---
# tasks file for ansible-role-jitsi-videobridge

- name: install base packages
  apt:
    pkg:
      - ufw
      - bmon
      - htop
      - default-jre
      - vim


- name: configure firewall rules
  ufw:
      rule: "{{ item.rule }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
  with_items:
      - { rule: 'allow', port: '22', proto: 'tcp' }
      - { rule: 'allow', port: '443', proto: 'tcp' }
      - { rule: 'allow', port: '10000:20000', proto: 'udp' }

- name: set logging
  ufw:
    logging: 'off'

- name: set ufw policy
  ufw:
    state: enabled
    policy: deny

- name: add gpg key for jitsi repo
  apt_key:
    url: https://download.jitsi.org/jitsi-key.gpg.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/jitsi.gpg

- name: add jitsi-meet stable apt repo
  apt_repository:
    repo: deb https://download.jitsi.org stable/
    state: present
    filename: jitsi

- name: install jitsi-videobridge2
  apt:
      name: jitsi-videobridge2
      state: present

- name: deploy videobridge config template
  template:
      src: templates/config.j2
      dest: /etc/jitsi/videobridge/config
  notify: restart videobridge service

- name: deploy videobridge sip-communicator properties
  template:
      src: templates/sip-communicator.properties.j2
      dest: /etc/jitsi/videobridge/sip-communicator.properties
  notify: restart videobridge service

- name: enable videobridge service
  systemd:
      name: jitsi-videobridge2
      enabled: yes
